### PR TITLE
Add sheet trimming script

### LINKED ISSUE #65: Trim whitespace on Institution and Name entries
This can be done manually on the spreadsheets but I think it'd be cleaner if it could automatically be handled. Whitespace results in issues like having only the white space student submission appear on the map, with the other, nonwhite space student submissions missing. 

Looking at the code it looks like both the institutions and the student names are already trimmed using .trim() but it clearly isn't working properly (and easily demonstratable) as it's happened a couple of times recently and messed up the map.

### PR DESCRIPTION
**Pull request by AndrewLester**
Closes #65

### CODE REVIEW

**Comment by JonathanOppenheimer** [comment]
Do you want to leave the trimming stuff inside of the script.js? It seems kinda redundant with this code not to mention that it was somewhat inconsistent. Unsure of best practice

**Comment by AndrewLester** [comment]
We would either have to move the trimming inside `script.js` to somewhere else in the file, as it only trims the data in one place while it needs to be trimmed throughout, or we could use this method which trims the data on the sheet itself. The first method would be a little bit strange to implement since it would cause the sheet's values to be different than what is actually used on the site.

**Comment by JonathanOppenheimer** [comment]
Sorry I phrased that poorly - what I was trying to say here is that I think we should delete the .trim() and trimming already present inside of script.js (not your pr) in favor of this solution for the reason that you explained, mainly that the sheet's value would be different from what's being used (and that it doesn't really work).

**Comment by AndrewLester** [comment]
Oh that is very true, I'll get on that. Just to be clear, the trimming in the script.js file won't mess anything up, it's just redundant.

**Comment by JonathanOppenheimer** [comment]
> Oh that is very true, I'll get on that. Just to be clear, the trimming in the script.js file won't mess anything up, it's just redundant.

ye this is what I meant -- that's all the changes I have personally

**Review by JonathanOppenheimer — APPROVED** [review]

**Review by ErikBoesen — APPROVED** [review]

**Pull request merged**
