### PR TITLE
Update repo to let in class of 2022

### LINKED ISSUE #73: Submit your (year goes here) destination does not change with the displayed map.
This tab in the bottom left
image
only displays the latest year (2021).

In case students what to submit their college location years after their graduation date, the form link and displayed text should change with the selected year seen here:
image

### PR DESCRIPTION
**Pull request by DannyOppenheimer**
Preliminary changes: basic functionality is there but there is no year statistics or student portraits.

### CODE REVIEW

**Comment by AndrewLester** [comment]
This code looks good, somethings being wonky with the papa parse and I'm gonna try to figure this out. I think it thinks certain strings are numbers and vice versa...
E.x: Try viewing "2022" on production right now.

**Comment by AndrewLester** [comment]
https://github.com/apc-mhs/seniormap/blob/e39e0e5db9dbb37a3d4bf0f2dd5de47c537d8237/js/scripts.js#L98
We may need to change this line to this:
```js
yearDocuments.set(yearDocument['Year'].toString(), {
```

**Comment by DannyOppenheimer** [comment]
Okay I'll take a look at that, also I forgot to make 2022 the default class when you open the website, so I will have to change that before this can be merged.

Edit: (I see now that it just comes into effect March 15th, nvm)

**Comment by DannyOppenheimer** [comment]
Close #73

**Review by AndrewLester — APPROVED** [review]

**Pull request merged**
